name: xbox-os
description: Ma console Linux style Xbox One
base-image: ghcr.io/ublue-os/main-generic # Utilise 'main-nvidia' si tu as une carte Nvidia
image-version: 39 # Basé sur Fedora 39 ou 40

modules:
  - type: rpm-ostree
    install:
      - xone
      - xpadneo
      - mangohud
      - gamescope
      - waydroid
      - bottles
      - flatpak
      - plymouth-theme-spinner # Pour l'écran de boot
      - python3-inotify # Pour surveiller les nouveaux jeux
    
  - type: default-flatpaks
    install:
      - org.pegasus_frontend.Pegasus
      - com.usebottles.bottles
